version: "1.0"
info:
  scaffold: Test123
  model: int-scaffold
services:
- serviceName: edge.vidi11may_publicrepo.integrations:Test123
  packages:
  - name: EdgeVidi11May_PublicRepo
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
